version: '2'

services:
    mongo:
        image: mongo:latest
        environment:
            - MONGO_DATA_DIR=/data/db
            - Mongo_LOG_DIR=/dev/null
        volumes:
            - ./mongo/data/db:/data/db
        ports:
            - "27017:27017"
        command: mongod --smallfiles

    backend:
        build:
            context: backend
            dockerfile: Dockerfile
        command: bash -c "npm install && gulp build && gulp"
        volumes:
            - ./backend/:/code/
            - ./logs:/logs
        ports:
            - "8000:8000"

    frontend:
        build:
            context: web
            dockerfile: Dockerfile
        command: bash -c "npm install && npm start"
        volumes:
            - ./web/:/code/
        ports:
            - "80:4200"

    swagger-ui:
        image: swaggerapi/swagger-ui
        ports:
            - "666:8080"
        environment:
            - API_URL = "http:/0.0.0.0:8000/public/api.yml"
        volumes:
            - ./swagger-ui/:/usr/share/nginx/html/
